name: CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SEVEN_API_KEY: '4MkFViZ2UdUaIbfZquju8BldsY5WSht1WlNLag2V4ZNApyYcC8zY0GsQwmkVAUmk'

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: stefanoeb/eslint-action@1.0.2

  build:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-horacio:$(date +%s)

  send-sms:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Send SMS'
        uses: seven-io/github-action-sms@master
        with:
          from: 'Horacio'
          text: 'OK letssss gooo ça marche bg'
          to: '+33783601717'
