name: CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    TWILIO_ACCOUNT_SID: 'SK0cd6bf1b9dcac779867f2b4c2a993afe'
    TWILIO_AUTH_TOKEN: '3dc588b3b4f781b485f437dda7dfb9f6'
    TWILIO_API_SECRET: 'Q6rwoE2b4mvUA27SCBu0CAOyqj9vesxN'

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: stefanoeb/eslint-action@1.0.2
    
  build:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-horacio:$(date +%s)
  
  send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          FROM_PHONE_NUMBER: '+14342150291'
          TO_PHONE_NUMBER: '+33783601717'
          message: 'Salut bg le build de my-horacio est sur le repos'