name: CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    TWILIO_ACCOUNT_SID: 'AC0becd613ff59be48cf4c44a6237f034c'
    TWILIO_AUTH_TOKEN: 'SK26680b349bc592cb680063ee3b05a917'
    TWILIO_API_SECRET: 'XkPW7nYaews9IirqYm4QWaj8j1OS6dXy'

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: stefanoeb/eslint-action@1.0.2
    
  build:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-horacio:$(date +%s)
  
  send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+14342150291'
          toPhoneNumber: '+33783601717'
          message: 'Salut bg le build de my-horacio est sur le repos' 